"""Update Register Table

Revision ID: 4f4ac3ba753a
Revises: aab4ad26756e
Create Date: 2023-11-29 03:42:52.929423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4ac3ba753a'
down_revision: Union[str, None] = 'aab4ad26756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registers', sa.Column('email', sa.String(), nullable=False))
    op.add_column('registers', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('registers', 'first_name')
    op.drop_column('registers', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registers', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('registers', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('registers', 'password')
    op.drop_column('registers', 'email')
    # ### end Alembic commands ###
